Feat: near loomies
PedroChaparro/loomies-backend pull request #58
Opened 2023-02-26 04:13 UTC by PedroChaparro

Includes: 

- [x] Update user struct to add the last time a loomie was generated by the user and the current generation timeout. 
- [x] Check if the user can generate new loomies according to the mentioned above fields.
- [ ] Generate loomies near the user area.
- [x] Update the "last time user generated loomies" and "current generation timeout" fields.

2023-02-27 04:14 UTC, SilviaPabon approved these changes
🎉

2023-03-01 22:41 UTC, Woynert requested changes

2023-03-02 01:57 UTC, PedroChaparro commented on api/.env.example
> +GAME_MAX_LOOMIES_PER_ZONE = int
Done

2023-03-03 18:33 UTC, andres123dbh approved these changes

2023-03-03 18:42 UTC, merged