Endpoint to reset password
PedroChaparro/loomies-backend pull request #70
Opened 2023-03-23 06:14 UTC by SilviaPabon

- 2 new fields in `users` collection: `resetPassCode` y`resetPassCodeExp` (time expiration) are included (the idea is in a future PR, create a new collection with fields like `resetPassCode` or `validationCode`)
- A code is created and added in `resetPassCode` when user request reset the password and its sended to the mail. To prove this, make a POST request to `/reset_password` including in the body the email that needs reset the password.
- Prove making a PUT request to `/reset_password`, to change password:
`{
	"email": "youremail@mail.com",
	"resetPassCode": "######",
	"password": "NewPassword"
}`

2023-03-23 23:57 UTC, andres123dbh approved these changes

2023-03-24 00:27 UTC, PedroChaparro requested changes

2023-03-24 00:27 UTC, PedroChaparro commented on api/routes/router.go
> +	engine.PUT("/reset_password", controllers.HandleResetPassword)
What do you think about: 

`/user/password/code` for the POST route and
`/user/password` for the PUT route.

2023-03-24 00:27 UTC, PedroChaparro commented on api/controllers/user.go
> +		fmt.Println(err)
Please, remove / comment those debug messages when the tasks is fully completed.

2023-03-24 00:27 UTC, PedroChaparro commented on api/controllers/user.go
> +	c.IndentedJSON(http.StatusOK, gin.H{"message": "New Code, to reset password, created and sended"})
Responses should follow this structure: 

```json
{
  "error": "boolean",
  "message": "String", 
  ... 
}
```

Please add the `error` field, at this way we can start standardize our API.

2023-03-24 11:13 UTC, PedroChaparro approved these changes
**Note to myself:** It's recommended to use camelCase to name JSON fields.

2023-03-24 11:14 UTC, merged

2023-03-30 19:57 UTC, Woynert commented
Please see #78