Endpoint validate if Loomie still exists
PedroChaparro/loomies-backend pull request #75
Opened 2023-03-24 22:57 UTC by andres123dbh

Try PR:
![image](https://user-images.githubusercontent.com/60190072/227649493-3591d285-48c5-4fe6-ad47-f2d17f349b1a.png)
Loomie exists:
![image](https://user-images.githubusercontent.com/60190072/227649576-7c3d5761-dc43-4b79-8175-ae2943efa109.png)
Loomie not exists:
![image](https://user-images.githubusercontent.com/60190072/227657780-d3c516d6-ca31-43ba-9026-0ffa26e65207.png)

2023-03-24 23:35 UTC, PedroChaparro requested changes
Check the requested changes and also, document your changes in the `.github/docs/openapi.yml` file, you can use the online swagger editor an then, copy the content of the file to out local file.

2023-03-24 23:35 UTC, PedroChaparro commented on api/routes/router.go
> +	engine.GET("/loomies/exists", middlewares.MustProvideAccessToken(), controllers.HandleValidateLoomieExists)
Usually `GET` routes doesn't receive any payload / JSON content, so, this endpoint should be `POST`.

2023-03-24 23:35 UTC, PedroChaparro commented on api/controllers/loomies.go
> +		c.AbortWithStatusJSON(http.StatusNotFound, gin.H{
Please, follow this schema for the responses on ALL the endpoints: 

```json
{
  "error": "boolean:", 
  "message": "string"
}
```

You can add other fields if needed, but always include the `error` and `message` fields.

2023-03-24 23:35 UTC, PedroChaparro commented on api/models/loomies.go
> +func ValidateLoomieExists(loomie_id string) (bool, error) {
You can just return the error, if there is an error you can infer that the Loomie doesn't exists.

2023-03-25 00:41 UTC, PedroChaparro requested changes

2023-03-25 00:41 UTC, PedroChaparro commented on .github/docs/openapi.yml
> +          description: Bad request. Mayby the loomie id field are empty.
Mayby -> Maybe
Are empty -> Is empty

2023-03-25 00:41 UTC, PedroChaparro commented on .github/docs/openapi.yml
> +          description: Loomie not exists in collection wild_loomies
Not exists -> Doesn't exists
Collection wild_loomies -> wild_loomies collection.

2023-03-25 00:41 UTC, PedroChaparro commented on .github/docs/openapi.yml
> +                      example: "Loomie no exists"
No exists -> Doesn't exists.

2023-03-25 00:41 UTC, PedroChaparro commented on api/controllers/loomies.go
> +		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": true, "message": "No Loomie ID"})
I suggest changing the message to "No Loomie ID was provided".

2023-03-25 00:41 UTC, PedroChaparro commented on api/controllers/loomies.go
> +			"message": "Loomie no exists",
No exists -> Doesn't exists.

2023-03-25 01:00 UTC, PedroChaparro commented on api/routes/router.go
> +	engine.POST("/loomies/exists", middlewares.MustProvideAccessToken(), controllers.HandleValidateLoomieExists)
What about receiving the Loomie Id as an endpoint parameter. Eg. `/loomies/exists/:id`. At this way the endpoint can use the `GET` method and can work without sending any JSON payload. Let me know if you'll implement this.

2023-03-25 01:02 UTC, PedroChaparro commented on api/routes/router.go
> +	engine.POST("/loomies/exists", middlewares.MustProvideAccessToken(), controllers.HandleValidateLoomieExists)
Also consider what @Woynert said (Returning the Loomie ID).

2023-03-25 02:17 UTC, PedroChaparro approved these changes

2023-03-27 22:55 UTC, SilviaPabon approved these changes

2023-03-27 22:56 UTC, merged